[package]
name = "bencher_google_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
bencher_valid.workspace = true
oauth2.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true
# Required due to feature unification
# https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
reqwest = { workspace = true, features = ["json", "rustls-tls"] }

[lints]
workspace = true
