[package]
name = "gen_types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = ["plus"]
plus = [
    "bencher_api/plus",
    "bencher_config/plus",
    "bencher_endpoint/plus",
    "bencher_json/plus",
]

[dependencies]
# Workspace
bencher_api.workspace = true
bencher_config.workspace = true
bencher_endpoint.workspace = true
bencher_json.workspace = true
bencher_logger.workspace = true
anyhow.workspace = true
clap.workspace = true
dropshot.workspace = true
literally.workspace = true
serde_json.workspace = true

[lints]
workspace = true
