[package]
name = "api_specs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = []
plus = [
    "bencher_endpoint/plus",
    "bencher_json/plus",
    "bencher_schema/plus",
    "dep:diesel",
    "dep:dropshot",
    "dep:schemars",
    "dep:serde",
]
sentry = ["bencher_schema/sentry"]
otel = ["bencher_endpoint/otel", "bencher_schema/otel"]

[dependencies]
bencher_endpoint = { workspace = true, optional = true }
bencher_json = { workspace = true, features = ["server", "schema", "db"], optional = true }
bencher_schema = { workspace = true, optional = true }
diesel = { workspace = true, optional = true }
dropshot = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
bencher_api_tests.workspace = true
bencher_json = { workspace = true, features = ["server", "schema", "db"] }
bencher_schema.workspace = true
diesel.workspace = true
http.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
