[package]
name = "rollback"
version = "0.1.0"
edition = "2021"
description = "Time Series Benchmarking"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
