version: "3.9"
services:
  bencher_api:
    build:
      context: ../services/api
      dockerfile: litestream.Dockerfile
    image: bencher-api-litestream
    container_name: bencher_api_litestream
    ports:
      - 61016:61016
    environment:
      # Set litestream configuration
      - LITESTREAM_DB_PATH=/data/bencher.db
      # Set configuration string or filepath
      # - BENCHER_CONFIG=
      # - BENCHER_CONFIG_PATH=
      # - SENTRY_DSN=
      # - LITESTREAM_REPLICA_URL=
      # - AWS_ACCESS_KEY_ID=
      # - AWS_SECRET_ACCESS_KEY=

  bencher_ui:
    build:
      context: ../services/console
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 3000:3000
    environment:
      # Set this to your actual host if different
      - BENCHER_API_URL=http://localhost:61016
      # - GOOGLE_ANALYTICS_ID=
    depends_on:
      - bencher_api
