app = "bencher-api"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "6s"

[build]
image = "registry.fly.io/bencher-api"

[env]
LITESTREAM_DB_PATH = "/data/bencher.db"

[[mounts]]
source = "bencher_data_machines"
destination = "/data"
processes = ["app"]

[[services]]
protocol = "tcp"
internal_port = 61016

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
