[package]
name = "bencher_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = ["plus", "sentry", "otel"]
plus = [
    "api_auth/plus",
    "api_checkout/plus",
    "api_organizations/plus",
    "api_projects/plus",
    "api_run/plus",
    "api_server/plus",
    "api_users/plus",
    "bencher_endpoint/plus",
    "bencher_config/plus",
    "bencher_json/plus",
    "bencher_otel_provider/plus",
    "bencher_schema/plus",
]
sentry = [
    "dep:sentry",
    "api_auth/sentry",
    "api_checkout/sentry",
    "api_organizations/sentry",
    "api_projects/sentry",
    "api_run/sentry",
    "api_server/sentry",
    "api_users/sentry",
    "bencher_config/sentry",
    "bencher_schema/sentry",
]
otel = [
    "dep:bencher_otel",
    "dep:bencher_otel_provider",
    "api_auth/otel",
    "bencher_schema/otel",
]

[dependencies]
# Workspace
api_auth.workspace = true
api_checkout.workspace = true
api_organizations.workspace = true
api_projects.workspace = true
api_run.workspace = true
api_server.workspace = true
api_users.workspace = true
bencher_config.workspace = true
bencher_endpoint.workspace = true
bencher_json = { workspace = true, features = ["server", "schema", "db"] }
bencher_logger.workspace = true
bencher_schema.workspace = true
bencher_otel = { workspace = true, optional = true }
bencher_otel_provider = { workspace = true, optional = true }
dropshot.workspace = true
sentry = { workspace = true, optional = true }
serde_yaml.workspace = true
slog.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread"] }
tokio-rustls.workspace = true

# https://github.com/diesel-rs/diesel/blob/ba2f567b038179d16cea939c0bcaaecc216ea947/diesel/Cargo.toml#L19
# https://github.com/tauri-apps/tauri/discussions/6183
# Always needed for Windows and all other targets when building a distroless image
[dependencies.libsqlite3-sys]
version = ">=0.17.2, <0.31.0"
features = ["bundled"]

[lints]
workspace = true

[[bin]]
name = "api"
path = "src/main.rs"
