[package]
name = "bencher_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
default-run = "api"

[features]
default = ["plus", "sentry"]
plus = [
    "bencher_json/plus",
    "dep:bencher_billing",
    "dep:bencher_license",
    "dep:reqwest",
]
sentry = ["dep:sentry"]
swagger = ["dep:literally"]

[dependencies]
# Workspace
async-trait.workspace = true
bencher_adapter.workspace = true
bencher_billing = { workspace = true, optional = true }
bencher_boundary.workspace = true
bencher_json = { workspace = true, features = ["full", "db", "schema"] }
bencher_license = { workspace = true, optional = true }
bencher_logger.workspace = true
bencher_plot.workspace = true
bencher_rbac.workspace = true
bencher_token.workspace = true
chrono.workspace = true
derive_more.workspace = true
diesel = { workspace = true, features = ["chrono", "sqlite"] }
dropshot.workspace = true
jsonwebtoken.workspace = true
literally = { workspace = true, optional = true }
once_cell.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
ordered-float.workspace = true
oso.workspace = true
rand.workspace = true
reqwest = { workspace = true, optional = true }
slog.workspace = true
slug.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread"] }
url.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
# Crate
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
aws-credential-types = "1.1"
aws-sdk-s3 = { version = "1.8", features = ["behavior-version-latest"] }
css-inline = "0.11"
diesel_migrations = "2.1"
hyper = "0.14"
http = "0.2"
mail-send = "0.4"
paste = "1.0"
sentry = { version = "0.32", optional = true }

[lints]
workspace = true

[[bin]]
name = "api"

[[bin]]
name = "swagger"
required-features = ["swagger"]
