[package]
name = "bencher_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
default-run = "api"

[features]
default = ["plus", "sentry"]
plus = [
    "bencher_json/plus",
    "dep:bencher_billing",
    "dep:bencher_license",
    "dep:bencher_plus",
]
sentry = ["dep:sentry"]
swagger = ["dep:literally"]

[dependencies]
# Workspace
bencher_adapter.workspace = true
bencher_billing = { workspace = true, optional = true }
bencher_json = { workspace = true, features = ["schema"] }
bencher_license = { workspace = true, optional = true }
bencher_plot.workspace = true
bencher_plus = { workspace = true, optional = true }
bencher_rbac.workspace = true
chrono.workspace = true
derive_more.workspace = true
jsonwebtoken.workspace = true
literally = { workspace = true, optional = true }
once_cell.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
ordered-float.workspace = true
oso.workspace = true
rand.workspace = true
slug.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread"] }
url.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
# Crate
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
aws-credential-types = "0.55"
aws-sdk-s3 = "0.28"
css-inline = "0.10"
diesel = { version = "2.0", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0"
dropshot = "0.9"
hyper = "0.14"
http = "0.2"
mail-send = "0.4"
sentry = { version = "0.31.5", optional = true }
slog = "2.7"
slog-term = "2.9"
statrs = "0.16"

[dev-dependencies]
pretty_assertions.workspace = true

[[bin]]
name = "api"

[[bin]]
name = "swagger"
required-features = ["swagger"]
