[package]
name = "api_oci"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = []
plus = [
    "api_auth/plus",
    "bencher_endpoint/plus",
    "bencher_oci_storage/plus",
    "bencher_schema/plus",
]
sentry = []
otel = ["dep:bencher_otel"]

[dependencies]
api_auth = { workspace = true }
bencher_endpoint = { workspace = true }
bencher_json = { workspace = true }
bencher_oci_storage = { workspace = true }
bencher_otel = { workspace = true, optional = true }
bencher_rbac = { workspace = true }
bencher_schema = { workspace = true }
bencher_token = { workspace = true }

bytes = { workspace = true }
dropshot = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }

[lints]
workspace = true
