[package]
name = "bencher_recaptcha"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
bencher_valid.workspace = true
chrono.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
