[package]
name = "bencher_output_protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = []
plus = []

[dependencies]
camino.workspace = true
thiserror.workspace = true

[lints]
workspace = true
