[package]
name = "bencher_github_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
bencher_valid.workspace = true
octocrab.workspace = true
serde.workspace = true
thiserror.workspace = true
# Crate
oauth2 = "5.0"

[lints]
workspace = true
