[package]
name = "bencher_bing_index"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true, features = ["rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url = { workspace = true, features = ["serde"] }

[lints]
workspace = true
