[package]
name = "gen_pkg"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = ["plus"]
plus = ["bencher_cli/plus"]

[dependencies]
bencher_cli.workspace = true
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
clap_mangen.workspace = true

[lints]
workspace = true
