[package]
name = "gen_installer"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
# Workspace
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
# Crate
minijinja = { version = "2.3", features = ["loader"] }
newline-converter = "0.3"

[lints]
workspace = true
