[package]
name = "test_netlify"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
# Workspace
bencher_json = { workspace = true, features = ["lite"] }
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
reqwest = { workspace = true, features = ["default"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
