[package]
name = "test_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = ["plus"]
plus = ["bencher_json/plus"]

[dependencies]
assert_cmd.workspace = true
bencher_json = { workspace = true, features = ["client"] }
anyhow.workspace = true
clap.workspace = true
pretty_assertions.workspace = true
reqwest = { workspace = true, features = ["blocking", "json", "rustls-tls"] }
serde_json.workspace = true

[lints]
workspace = true
