[typescript.type_mappings]
# Typed UUIDs
"Uuid" = "string"
"OrganizationUuid" = "Uuid"
"ProjectUuid" = "Uuid"
"ReportUuid" = "Uuid"
"PlotUuid" = "Uuid"
"BranchUuid" = "Uuid"
"TestbedUuid" = "Uuid"
"BenchmarkUuid" = "Uuid"
"MeasureUuid" = "Uuid"
"MetricUuid" = "Uuid"
"ThresholdUuid" = "Uuid"
"ModelUuid" = "Uuid"
"AlertUuid" = "Uuid"
"UserUuid" = "Uuid"
"TokenUuid" = "Uuid"
# Other types
"DateTime" = "string"
"OrderedFloat" = "number"
"BigInt" = "number"
"TimestampMillis" = "number"
