[typescript.type_mappings]
# Typed UUIDs
"Uuid" = "string"
"OrganizationUuid" = "Uuid"
"SsoUuid" = "Uuid"
"ProjectUuid" = "Uuid"
"ReportUuid" = "Uuid"
"PlotUuid" = "Uuid"
"BranchUuid" = "Uuid"
"HeadUuid" = "Uuid"
"TestbedUuid" = "Uuid"
"BenchmarkUuid" = "Uuid"
"MeasureUuid" = "Uuid"
"MetricUuid" = "Uuid"
"ThresholdUuid" = "Uuid"
"ModelUuid" = "Uuid"
"AlertUuid" = "Uuid"
"UserUuid" = "Uuid"
"TokenUuid" = "Uuid"
"SpecUuid" = "Uuid"
"RunnerUuid" = "Uuid"
"JobUuid" = "Uuid"
# Typed Slugs
"Slug" = "string"
"OrganizationSlug" = "Slug"
"ProjectSlug" = "Slug"
"BranchSlug" = "Slug"
"TestbedSlug" = "Slug"
"BenchmarkSlug" = "Slug"
"MeasureSlug" = "Slug"
"UserSlug" = "Slug"
"RunnerSlug" = "Slug"
"SpecSlug" = "Slug"
# Resource ID
"ResourceId" = "Uuid | Slug"
# Name ID
"NameId" = "Uuid | Slug | string"
# Other types
"DateTime" = "string"
"ImageReference" = "string"
"Utf8PathBuf" = "string"
"OrderedFloat" = "number"
"BigInt" = "number"
"TimestampMillis" = "number"
"Cpu" = "number"
"Disk" = "number"
"Memory" = "number"
"GracePeriod" = "number"
"HeartbeatTimeout" = "number"
